apiVersion: v1
kind: Service
metadata:
  name: ocsp-svc
  labels:
    app: ocsp-svc
spec:
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: ocsp-svc

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ocsp-svc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ocsp-svc
  template:
    metadata:
      labels:
        app: ocsp-svc
    spec:
      containers:
      - name: ocsp-svc
        image: docker.io/cfssl/cfssl:latest
        command: ["cfssl", "ocspserve"]
        args: ["-address=", "-port=8080", "-loglevel=0", "-responses=/etc/ocsp/responses.txt"]
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: config-volume
          mountPath: /etc/ocsp
      volumes:
      - name: config-volume
        configMap:
          name: ocsp-responses

---

apiVersion: v1
data:
  responses.txt: |
    MIIG3woBAKCCBtgwggbUBgkrBgEFBQcwAQEEggbFMIIGwTCCATuhgZYwgZMxCzAJBgNVBAYTAkNBMRAwDgYDVQQIEwdPbnRhcmlvMQ8wDQYDVQQHEwZPdHRhd2ExFTATBgNVBAoTDEVsdmluJ3MgRGVtbzEkMCIGA1UECxMbRWx2aW4ncyBEZW1vIE9DU1AgUmVzcG9uZGVyMSQwIgYDVQQDExtFbHZpbidzIERlbW8gT0NTUCBSZXNwb25kZXIYDzIwMjAwMzIyMjEwMjAwWjCBjjCBizBNMAkGBSsOAwIaBQAEFDtqzj1tA68ZJUDszfzszn7Xe4GjBBQiMGgiCzumC0cLrmKvgFOwtAc26AIUBdTMVvyzOD6eaBRPVTp3p3d0DaehFhgPMjAyMDAzMjIxOTM4MTBaoAMKAQQYDzIwMjAwMzIyMjEwMDAwWqARGA8yMDIwMDMyNjIxMDAwMFowDQYJKoZIhvcNAQELBQADggEBAEEEDNn+PuWMh2AGn6Eaqt0kymOYCHcTay5xukwCTFmy+ptKz+t/pXWkzDrhOcKkJEpwr9mHkyNT5JBzLAn8DIgICNYntBk7gw59WWToHqaA5ie6HXA38TV99v47w7kv/lgHdceMbzpS7F1t5a1aI9yvXRU7NThirLog1oyJToY9ViNgSCThzEppJB0Gd6/da9s3PDX14xfC3+XoD63unnmsApbs5F4D2XlNHuzT4V7tw8bB5n6pO7tpnbFZEmOTwrvvAs6ETw9RN9zLmiB+G7EDgNHD451LE6q64HhjYZ9XJnuw9nYvtNiM1HUBRanP1CPXt2R3D1uJbrTFhWQoyuugggRqMIIEZjCCBGIwggNKoAMCAQICFHNp5JEiRQl/I2Wq1BPrmvPZ3URbMA0GCSqGSIb3DQEBCwUAMIGVMQswCQYDVQQGEwJDQTEQMA4GA1UECBMHT250YXJpbzEPMA0GA1UEBxMGT3R0YXdhMRUwEwYDVQQKEwxFbHZpbidzIERlbW8xJTAjBgNVBAsTHEVsdmluJ3MgRGVtbyBJbnRlcm1lZGlhdGUgQ0ExJTAjBgNVBAMTHEVsdmluJ3MgRGVtbyBJbnRlcm1lZGlhdGUgQ0EwHhcNMjAwMzIyMTYyMTAwWhcNMjEwMzIyMTYyMTAwWjCBkzELMAkGA1UEBhMCQ0ExEDAOBgNVBAgTB09udGFyaW8xDzANBgNVBAcTBk90dGF3YTEVMBMGA1UEChMMRWx2aW4ncyBEZW1vMSQwIgYDVQQLExtFbHZpbidzIERlbW8gT0NTUCBSZXNwb25kZXIxJDAiBgNVBAMTG0VsdmluJ3MgRGVtbyBPQ1NQIFJlc3BvbmRlcjCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAMDsLGAof4nX9ymLCbrruxUO3Q9d894lsnhHFt5wZcJOoYVxjiMmAsG0cVEtBfkOWaSpU1g3xsnxpewx7el2icPQaV3kQfL6LHDfie3yid+JdzYOOlRdUmlOjW/vI9cF5Z8TjTCyh5E/R5FWLUJgFmd/Y4Ye1QBK0uFCRUWc8MC5LLnvRDcJ3BS/NIjjlY18qV1ypEZzZJcOBonlP8TLJyi+hsr/QYgPNlWOlfnYV3p7dfh3Tgdd1n+v/zvhQkH32OvP+hMkQRZBH/3J7dED5XArtO8tCoxNd8/zDuZewm1McMCOzRvKBabY1Qjt9oJSAjvVfCou20lRUsLw+zTYo10CAwEAAaOBqTCBpjAOBgNVHQ8BAf8EBAMCB4AwEwYDVR0lBAwwCgYIKwYBBQUHAwkwDAYDVR0TAQH/BAIwADAdBgNVHQ4EFgQUBIXEveoUVCKHhLtem/Qbjuq1JeIwHwYDVR0jBBgwFoAUIjBoIgs7pgtHC65ir4BTsLQHNugwMQYIKwYBBQUHAQEEJTAjMCEGCCsGAQUFBzABhhVodHRwOi8vbG9jYWxob3N0OjgwODAwDQYJKoZIhvcNAQELBQADggEBAA8IiehIgpigoxfY5YWfIdrE6U2farvsgiO84zBCRkva9W+QzR9gj6PC9D2QIMbNXtO7aUm/KcGBSuyhdWNBa20e9hWweODs92sTua11Tfzp+PhmzFJy+aVZ4zOD4AOPUGtjQAJqKnzpzmLhh32gSsjykyaZZn+Pw7B3W24PXGCmnyK6U5Q96Ilr6n+cYmQDfqkPawuBikS9pgSYWiq3QpqkPu3Zh5Y6mxVoqFNz78i1rk9cPcFQ4Pt2qW125C47UexImBvgpu3P7kJwsBxgGGu/aiwAJ4/xQNsinlNku0vNSxRCJqNWtO45NF9mbmmfUHicOmgstQLCPy34jYuw74U=
    MIIGxwoBAKCCBsAwgga8BgkrBgEFBQcwAQEEggatMIIGqTCCASOhgZYwgZMxCzAJBgNVBAYTAkNBMRAwDgYDVQQIEwdPbnRhcmlvMQ8wDQYDVQQHEwZPdHRhd2ExFTATBgNVBAoTDEVsdmluJ3MgRGVtbzEkMCIGA1UECxMbRWx2aW4ncyBEZW1vIE9DU1AgUmVzcG9uZGVyMSQwIgYDVQQDExtFbHZpbidzIERlbW8gT0NTUCBSZXNwb25kZXIYDzIwMjAwMzIyMjEwMjAwWjB3MHUwTTAJBgUrDgMCGgUABBQ7as49bQOvGSVA7M387M5+13uBowQUIjBoIgs7pgtHC65ir4BTsLQHNugCFEoDVIjjNaINLLeP/Wuz+Uytq0r0gAAYDzIwMjAwMzIyMjEwMDAwWqARGA8yMDIwMDMyNjIxMDAwMFowDQYJKoZIhvcNAQELBQADggEBADVPUJR2rmhLuYHpoDB2E4jmJrWbBn/jAsUfvMpBsUH08C0U6gcpdp6SYZIBsGN2VqYoMha8Axo7MoLBMCjaDxDuWdbfPV3SyogUNf9RHfqpr6Q7LCKg07aMf8Fh+QXGpQvlLmKMgIPESw7GYwhQGjzm5zxhTvsFS3grLUT7wxYv7iGzS34YGiO1w+1gq475LuAAey/kBk+u36kLs0RIJQ9cYmD4jOfOy5gY/NiBzhHnfoODrnn9NiJ0y82FqSMdD3vq0e7cGRHi/e/pcadZjcCKuAMHxcAYhoRxsiCx1dP6Y4tTMXEgt8VALWp/FxmPcxL9t+PyMfYf2cJSJI/QH+GgggRqMIIEZjCCBGIwggNKoAMCAQICFHNp5JEiRQl/I2Wq1BPrmvPZ3URbMA0GCSqGSIb3DQEBCwUAMIGVMQswCQYDVQQGEwJDQTEQMA4GA1UECBMHT250YXJpbzEPMA0GA1UEBxMGT3R0YXdhMRUwEwYDVQQKEwxFbHZpbidzIERlbW8xJTAjBgNVBAsTHEVsdmluJ3MgRGVtbyBJbnRlcm1lZGlhdGUgQ0ExJTAjBgNVBAMTHEVsdmluJ3MgRGVtbyBJbnRlcm1lZGlhdGUgQ0EwHhcNMjAwMzIyMTYyMTAwWhcNMjEwMzIyMTYyMTAwWjCBkzELMAkGA1UEBhMCQ0ExEDAOBgNVBAgTB09udGFyaW8xDzANBgNVBAcTBk90dGF3YTEVMBMGA1UEChMMRWx2aW4ncyBEZW1vMSQwIgYDVQQLExtFbHZpbidzIERlbW8gT0NTUCBSZXNwb25kZXIxJDAiBgNVBAMTG0VsdmluJ3MgRGVtbyBPQ1NQIFJlc3BvbmRlcjCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAMDsLGAof4nX9ymLCbrruxUO3Q9d894lsnhHFt5wZcJOoYVxjiMmAsG0cVEtBfkOWaSpU1g3xsnxpewx7el2icPQaV3kQfL6LHDfie3yid+JdzYOOlRdUmlOjW/vI9cF5Z8TjTCyh5E/R5FWLUJgFmd/Y4Ye1QBK0uFCRUWc8MC5LLnvRDcJ3BS/NIjjlY18qV1ypEZzZJcOBonlP8TLJyi+hsr/QYgPNlWOlfnYV3p7dfh3Tgdd1n+v/zvhQkH32OvP+hMkQRZBH/3J7dED5XArtO8tCoxNd8/zDuZewm1McMCOzRvKBabY1Qjt9oJSAjvVfCou20lRUsLw+zTYo10CAwEAAaOBqTCBpjAOBgNVHQ8BAf8EBAMCB4AwEwYDVR0lBAwwCgYIKwYBBQUHAwkwDAYDVR0TAQH/BAIwADAdBgNVHQ4EFgQUBIXEveoUVCKHhLtem/Qbjuq1JeIwHwYDVR0jBBgwFoAUIjBoIgs7pgtHC65ir4BTsLQHNugwMQYIKwYBBQUHAQEEJTAjMCEGCCsGAQUFBzABhhVodHRwOi8vbG9jYWxob3N0OjgwODAwDQYJKoZIhvcNAQELBQADggEBAA8IiehIgpigoxfY5YWfIdrE6U2farvsgiO84zBCRkva9W+QzR9gj6PC9D2QIMbNXtO7aUm/KcGBSuyhdWNBa20e9hWweODs92sTua11Tfzp+PhmzFJy+aVZ4zOD4AOPUGtjQAJqKnzpzmLhh32gSsjykyaZZn+Pw7B3W24PXGCmnyK6U5Q96Ilr6n+cYmQDfqkPawuBikS9pgSYWiq3QpqkPu3Zh5Y6mxVoqFNz78i1rk9cPcFQ4Pt2qW125C47UexImBvgpu3P7kJwsBxgGGu/aiwAJ4/xQNsinlNku0vNSxRCJqNWtO45NF9mbmmfUHicOmgstQLCPy34jYuw74U=
kind: ConfigMap
metadata:
  name: ocsp-responses
  namespace: ingress-nginx
